### ISSUE TITLE
Bewitchment Brewing still isnt working! Pls fix :(

### ISSUE THREAD

**Issue by Brokengamer** [NordicGamerFE/Ocean-Outlast#96] opened 2021-05-27 15:44 UTC
The water in the witches cauldron turns brown and thats about all you can do.. 
Brewing isnt working in general

**Comment by NordicGamerFE** [comment] 2021-06-21 00:31
do you have sufficient altar power for the brew you are trying to make

**Comment by djozis** [comment] 2021-07-03 09:01
Duplicate of #94 ?

**Closed as completed** 2021-10-07 14:48 UTC
