### ISSUE TITLE
Weird player aim discrepancy

### ISSUE THREAD

**Issue by CheesyButler95** [NordicGamerFE/Ocean-Outlast#76] opened 2020-12-30 06:44 UTC
Version: Expert - V.54

Description:
I don't know what causes it exactly, but generally just about every time when trying to use a bow after playing for a while (over an hour usually) the arrows shoot out as if I was aiming like 20 degrees lower, consistently.  this also applies to directionally dropping items, although it appears to have no effect on melee-attacking mobs.
Saving/quitting out of the world, and then loading back in fixes it completely, at least for the time being, but it eventually triggers again, for whatever reason.

I have a super low-end set up, and so very frequently the game freezes for a second or two and then comes back, and there's a chance that that has something to do with it, but I'm not sure.

Did you add additional mods?
no

Edit: I really wang-doodled the mouse around while teleporting and travelling between dimensions, it appears to have no effect.

**Comment by FagSoft** [comment] 2021-05-16 15:36
I can confirm this one. I've had it happen quite a few times on the SMP world I set up, but haven't experienced it in the single-player world. Not sure if this is caused by some in-world blocks, or if it's a server vs SP issue, but it's not based upon playing time at least.
I've had a lot more hours played on single-player than on the server, and it can happen after 10 minutes or after several hours on the server. Can temporary fix it by reconnecting to the server, but it doesn't seem to hold long. Afraid I don't have too much data on this one, as it only started to happen the day before yesterday. 

Should be noted that this bug doesn't only apply to shooting arrows or throwing/dropping items, but also when trying to interact with blocks. Using compacting drawers I found that there's some really odd interaction going on. In short, the discrepancy does not affect which block you're targetting, only where the actual click is registered on that block. So that if I tried to pick out a Iron Block from the drawer, I would either get an ingot or a nugget. However, if I tried to pull out an ingot, I wouldn't get anything despite there being a drawer below as well. I assume this is because the activation point was registered outside of the field of the block itself.

**Comment by hipsterbaby** [comment] 2021-08-17 12:20
I've noticed this as well, my theory is that it comes from swimming in the water (not old school style but by holding sprint in the water and actually swimming). After jumping out of the water, the game just thinks you're still 1 block tall so it registers items and arrows as coming from where you'd be if you were still swimming. Not sure if it's correct or not but it makes sense to me.

**Comment by k-al** [comment] 2021-08-31 11:31
Yes, it seems to have to do with the swimming.
Swimming again (sprint swim) and than carefully get out of the water (not sprinting) mostly fixes this, but you may have to try multiple times.
Relogging works too.

**Comment by john13210** [comment] 2021-12-08 10:21
btw this sometimes happens in vanilla

**Comment by NordicGamerFE** [comment] 2021-12-08 15:36
I've spoken with the creator of better diving and he thinks this is because of his mod, I doubt he's actually going to do something with that tho as he has pretty much dropped 1.12 support. There for I am going to close this

**Closed as completed by NordicGamerFE** 2021-12-08 15:36 UTC
Labels: bug, Testing Needed, Contributions Welcome, What the fuck?, Reported To Mod
